### ISSUE TITLE
Wrong counts

### ISSUE THREAD

**Issue by Decat-SimonA** [ChrisPenner/wc#4]
Tested on the enwik8 file from http://mattmahoney.net/dc/textdata.html

```sh
> stack run simple ~/Downloads/enwik8
1128023 13303079 99621832 /home/foo/Downloads/enwik8

> stack run lazy ~/Downloads/enwik8  
1128023 13306747 100000000 /home/foo/Downloads/enwik8

> wc ~/Downloads/enwik8
1128023  13303065 100000000 /home/foo/Downloads/enwik8
```

**Comment by ChrisPenner** [comment]
Very interesting! Thanks for this; I had a hard time finding a decent collection of sufficiently rich UTF-8 when I was testing!

Although the start of the post claims correctness with `wc` as a core goal; that's relaxed later in the article when I try out some of the UTF-8 hacks and decide to only consider ASCII whitespace. It's very possible whichever version of `wc` you're using considers certain UTF-8 whitespace characters differently; it's also evident you're using a different version of `wc` since you didn't need to pass `-m` as a flag.

As for the simple version I'm pretty curious what `words` and `lines` do that would result in such different answers!

If you're able to find any other insights to this I'd love to hear about them, but at the very least thanks for the test files.

Not sure there's really any actionable items here, so I'll close for now, but maybe I'll come back to this later 😄

**Comment by hugosenari** [comment]
`AAàAAA`

```bash
wc
1 1 8 a.txt
```
```bash
./wc-exe lazy
1 2 8 a.txt
```
```bash
./wc-exe simple
1 1 7 a.txt
```

**Comment by ChrisPenner** [comment]
Make sure you're using `lazy-utf` btw; but there was a bug there too. Looks like certain continuation bytes are being interpreted as spaces, which seems weird to me, not sure why that is.

Regardless I just changed the `countByteUTF8` function to use mempty when counting continuation bytes and it seems to have sorted that bug out (though it's entirely possible there are still others lurking within). Thanks for the help!

**Comment by hugosenari** [comment]
I don't know why, I couldn't run with hiphen on Linux. ie:

./wc-exe lazy runs.fine.txt

./wc-exe lazy-utf8 fails.reach. utf8.version.txt

But is other issue ;-)

**Comment by ChrisPenner** [comment]
It's called `lazy-utf` not `lazy-utf8`; which might have something to do with it :)
